image: ghcr.io/cirruslabs/flutter:3.35.3

stages:
  - build

build_apk:
  stage: build
  script:
    - flutter clean
    - flutter pub get
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
    expire_in: 1 week