name: granth_flutter
description: A new Book selling  Flutter application.
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # COMMON
  carousel_slider_plus: ^7.0.1
  fancy_shimmer_image: ^2.0.2
  carousel_slider: ^5.0.0
  nb_utils: ^7.0.8
  url_launcher: ^6.3.1
  flutter_html: ^3.0.0-beta.2
  http: ^1.2.2
  share_plus: ^10.1.3
  package_info_plus: ^8.1.2
  connectivity_plus: ^6.1.1

  flutter_downloader: ^1.12.0

  # Animated Text
  animated_text_kit: ^4.2.2

  # Firebase
  firebase_core: ^3.9.0
  firebase_crashlytics: ^4.2.0

  # STATE MANAGEMENT
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0

  # IMAGES
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

  # UI
  google_fonts: ^6.2.1

  #VOICE SEARCH
  speech_to_text: ^7.0.0

  # DOWNLOAD
  internet_file: ^1.2.0
#  flutter_file_downloader: ^1.2.1
  path_provider: ^2.1.5
  universal_html: ^2.2.4

  # FIREBASE MESSAGING
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1

  # PDF File
  flutter_pdfview: ^1.4.0

  # EPUB File
  flutter_epub_viewer: ^1.1.5
  epub_view: ^3.2.0
  # DATABASE
  sqflite: ^2.4.1

  #payment
  razorpay_flutter: ^1.3.7
  flutter_stripe: ^11.3.0
#  paytm:
  #    git:
  #      url: https://github.com/iqonic-design/Paytm-All-in-one-flutter-sdk-master.git
  #      ref: main
  flutterwave_standard:
    git:
      url: https://github.com/iqonic-design/flutterwave_standard.git
      ref: main

  #Google ads
#  google_mobile_ads: ^5.2.0

  #Animation
  lottie: ^3.3.0

  #permission
  permission_handler: ^11.3.1
  device_info_plus: ^11.2.0

  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  mobx_codegen: ^2.7.0
  flutter_launcher_icons: 0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app_images/app_logo.png"
  min_sdk_android: 21
  #flutter packages pub run build_runner build --delete-conflicting-outputs
dependency_overrides:
  http: ^1.2.2
  intl: ^0.20.1


flutter:
  uses-material-design: true
  assets:
    - images/
    - images/app_icons/
    - images/app_images/
    - images/flag/
    - images/lottie/

