// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLuxkBK6RTOmOeNihheOdBg1CDuUZhq1s',
    appId: '1:336224681714:web:0928860e0a885973d79a6b',
    messagingSenderId: '761645457564',
    projectId: 'book-guard',
    authDomain: 'book-guard.firebaseapp.com',
    storageBucket: 'book-guard.firebasestorage.app',
    measurementId: 'G-QNNBJZ83BQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLuxkBK6RTOmOeNihheOdBg1CDuUZhq1s',
    appId: '1:761645457564:android:535afd3ec7fe25a79c4d59',
    messagingSenderId: '761645457564',
    projectId: 'book-guard',
    storageBucket: 'book-guard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE6MxmCqekyO7l5e8SIMQ2MX6-FATUH-Q',
    appId: '1:761645457564:ios:ce7be3d32595160b9c4d59',
    messagingSenderId: '761645457564',
    projectId: 'book-guard',
    storageBucket: 'book-guard.firebasestorage.app',
    iosBundleId: 'com.book.guard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2O_iTipFk4-u13R6RQjugzjod1BqhknA',
    appId: '1:761645457564:ios:c03606a6b51a8adfd79a6b',
    messagingSenderId: '761645457564',
    projectId: 'book-guard',
    storageBucket: 'book-guard.firebasestorage.app',
    iosBundleId: 'com.book.guard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5vCg_SeKyDkrzyL4v_LNMxmzJ9EaIE9M',
    appId: '1:761645457564:web:a9db6b7ae070048ed79a6b',
    messagingSenderId: '761645457564',
    projectId: 'book-guard',
    authDomain: 'book-guard.firebaseapp.com',
    storageBucket: 'book-guard.firebasestorage.app',
    measurementId: 'G-C28ZBZ60L6',
  );

}